# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RACC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RACC
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'RACCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RACCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
